# Generated by Django 4.1.2 on 2023-11-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_sage300credential_importsetting_fylecredential_and_more'),
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentfieldsetting',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, related_name='dependent_field_settings', to='workspaces.workspace'),
        ),
    ]
