# Generated by Django 4.1.2 on 2023-11-02 09:29

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_sage300credential_importsetting_fylecredential_and_more'),
        ('fyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentFieldSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_import_enabled', sage_desktop_api.models.fields.BooleanFalseField(default=True, help_text='Is Import Enabled')),
                ('project_field_id', sage_desktop_api.models.fields.IntegerNotNullField(help_text='Fyle Source Field ID')),
                ('cost_code_field_name', sage_desktop_api.models.fields.StringNotNullField(help_text='Fyle Cost Code Field Name', max_length=255)),
                ('cost_code_field_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Fyle Cost Code Field ID', max_length=255)),
                ('cost_code_placeholder', models.TextField(blank=True, help_text='Placeholder for Cost code', null=True)),
                ('cost_category_field_name', sage_desktop_api.models.fields.StringNotNullField(help_text='Fyle Cost Category Field Name', max_length=255)),
                ('cost_category_field_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Fyle Cost Category Field ID', max_length=255)),
                ('cost_category_placeholder', models.TextField(blank=True, help_text='Placeholder for Cost Category', null=True)),
                ('last_successful_import_at', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Last Successful Import At', null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'dependent_field_settings',
            },
        ),
    ]
