# Generated by Django 4.1.2 on 2023-11-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_importsetting_workspace'),
        ('fyle', '0002_dependentfieldsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentfieldsetting',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, related_name='dependent_field_settings', to='workspaces.workspace'),
        ),
    ]
