# Generated by Django 4.1.2 on 2023-11-06 18:16

from django.db import migrations, models
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0002_dependentfieldsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_number',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Expense payment number', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='report_title',
            field=models.TextField(blank=True, help_text='Report title', null=True),
        ),
    ]
