# Generated by Django 4.1.2 on 2024-05-14 14:18

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0002_expense_is_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensefilter',
            name='custom_field_type',
            field=sage_desktop_api.models.fields.StringOptionsField(choices=[('SELECT', 'SELECT'), ('NUMBER', 'NUMBER'), ('TEXT', 'TEXT'), ('BOOLEAN', 'BOOLEAN')], default='', help_text='Custom field type', max_length=255, null=True),
        ),
    ]
