# Generated by Django 4.1.2 on 2024-05-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0003_alter_expensefilter_custom_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='settlement_id',
        ),
    ]
