# Generated by Django 4.1.2 on 2023-11-06 18:19

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0003_expense_payment_number_expense_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=sage_desktop_api.models.fields.FloatNullField(help_text='Home Amount', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='foreign_amount',
            field=sage_desktop_api.models.fields.FloatNullField(help_text='Foreign Amount', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='foreign_currency',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Foreign Currency', max_length=5, null=True),
        ),
    ]
