# Generated by Django 4.1.2 on 2023-11-06 18:21

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_alter_expense_amount_alter_expense_foreign_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Vendor', max_length=255, null=True),
        ),
    ]
