# Generated by Django 4.1.2 on 2023-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_sage300credential_importsetting_fylecredential_and_more'),
        ('fyle', '0005_alter_expense_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='workspace',
            field=models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
    ]
