# Generated by Django 4.2.20 on 2025-04-16 16:36

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0006_expense_imported_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='imported_from',
            field=sage_desktop_api.models.fields.StringNullField(choices=[('WEBHOOK', 'WEBHOOK'), ('DASHBOARD_SYNC', 'DASHBOARD_SYNC'), ('DIRECT_EXPORT', 'DIRECT_EXPORT'), ('BACKGROUND_SCHEDULE', 'BACKGROUND_SCHEDULE'), ('INTERNAL', 'INTERNAL')], help_text='Imported from source', max_length=255, null=True),
        ),
    ]
