# Generated by Django
from django.db import migrations
from apps.internal.helpers import safe_run_sql


sql_files = [
    # Global Shared Functions
    'fyle-integrations-db-migrations/common/global_shared/functions/json_diff.sql',
    'fyle-integrations-db-migrations/common/global_shared/functions/log_delete_event.sql',

    # Global Views
    'fyle-integrations-db-migrations/common/global_shared/views/extended_category_mappings_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/extended_employee_mappings_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/extended_mappings_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/prod_workspaces_view.sql',

    # Global Alert Views
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/_import_logs_fatal_failed_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/import_logs_fatal_failed_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/ormq_count_view.sql',
    'fyle-integrations-db-migrations/common/global_shared/views/alerts/repetition_error_count_view.sql',

    # Grouped Functions
    'fyle-integrations-db-migrations/common/sage300_qbd/functions/trigger_auto_import_export.sql',
    'fyle-integrations-db-migrations/common/sage300_qbd/functions/ws_org_id.sql',
    'fyle-integrations-db-migrations/common/sage300_qbd/functions/ws_search.sql',

    # Grouped Alert Views
    'fyle-integrations-db-migrations/common/sage300_qbd/views/alerts/inactive_workspaces_view.sql',

    # Sage300 Functions
    'fyle-integrations-db-migrations/sage300/functions/delete_workspace.sql',
    'fyle-integrations-db-migrations/sage300/functions/log_update_event.sql',
    'fyle-integrations-db-migrations/sage300/functions/trigger_auto_import.sql',

    # Sage300 Views
    'fyle-integrations-db-migrations/sage300/views/prod_active_workspaces_view.sql',

    # Sage300 Alert Views
    'fyle-integrations-db-migrations/sage300/views/alerts/_django_queue_fatal_tasks_view.sql',
    'fyle-integrations-db-migrations/sage300/views/alerts/_django_queue_in_progress_tasks_view.sql',
    'fyle-integrations-db-migrations/sage300/views/alerts/django_queue_fatal_tasks_view.sql',
    'fyle-integrations-db-migrations/sage300/views/alerts/django_queue_in_progress_tasks_view.sql',

    # Sage300 Triggers
    'fyle-integrations-db-migrations/sage300/triggers/update_logs.sql'

]


class Migration(migrations.Migration):
    dependencies = [
        ('accounting_exports', '0004_merge_20240723_1115'),
        ('fyle', '0005_expense_is_posted_at_null'),
        ('mappings', '0002_version_commitment_item_alter_version_table'),
        ('sage300', '0007_costcategory_cost_category_code_and_more'),
        ('users', '0001_initial'),
        ('workspaces', '0007_add_created_at_to_user_sql')
    ]
    operations = safe_run_sql(sql_files)
