# Generated by Django
from django.db import migrations
from apps.internal.helpers import safe_run_sql
sql_files = [
    'fyle-integrations-db-migrations/sage300/views/alerts/_account_export_stuck_view.sql',
    'fyle-integrations-db-migrations/sage300/views/alerts/account_export_stuck_view.sql'
]
class Migration(migrations.Migration):
    dependencies = [('internal', '0006_auto_generated_sql')]
    operations = safe_run_sql(sql_files)
