# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('workspaces', '0014_featureconfig_is_job_status_sync_enabled'), ('internal', '0013_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE feature_configs SET is_job_status_sync_enabled = FALSE;
            """
        )
    ]
