# Generated by Django 4.1.2 on 2023-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('account', sage_desktop_api.models.fields.IntegerNullField(help_text='version for account', null=True)),
                ('job', sage_desktop_api.models.fields.IntegerNullField(help_text='version for job', null=True)),
                ('standard_category', sage_desktop_api.models.fields.IntegerNullField(help_text='version for standard category', null=True)),
                ('standard_cost_code', sage_desktop_api.models.fields.IntegerNullField(help_text='version for standard costcode', null=True)),
                ('cost_category', sage_desktop_api.models.fields.IntegerNullField(help_text='version for job category', null=True)),
                ('cost_code', sage_desktop_api.models.fields.IntegerNullField(help_text='version for costcode', null=True)),
                ('vendor', sage_desktop_api.models.fields.IntegerNullField(help_text='version for vendor', null=True)),
                ('commitment', sage_desktop_api.models.fields.IntegerNullField(help_text='version for commitment', null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
