# Generated by Django 4.1.2 on 2023-12-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mappings', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='workspace',
            field=models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='importlog',
            unique_together={('workspace', 'attribute_type')},
        ),
    ]
