# Generated by Django 4.1.2 on 2023-11-28 09:49

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingexport',
            old_name='sage_300_errors',
            new_name='sage300_errors',
        ),
        migrations.AddField(
            model_name='accountingexport',
            name='export_id',
            field=sage_desktop_api.models.fields.StringNullField(help_text='id of the exported expense', max_length=255, null=True),
        ),
    ]
