# Generated by Django 4.1.2 on 2024-07-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0003_alter_accountingexport_type'),
        ('accounting_exports', '0003_error_repetition_count'),
    ]

    operations = [
    ]
