# Generated by Django 4.2.20 on 2025-04-08 08:53

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0004_merge_20240723_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingexport',
            name='triggered_by',
            field=sage_desktop_api.models.fields.StringOptionsField(choices=[('WEBHOOK', 'WEBHOOK'), ('DASHBOARD_SYNC', 'DASHBOARD_SYNC'), ('DIRECT_EXPORT', 'DIRECT_EXPORT'), ('BACKGROUND_SCHEDULE', 'BACKGROUND_SCHEDULE')], default='', help_text='Triggered by', max_length=255, null=True),
        ),
    ]
