# Generated by Django 4.2.20 on 2025-04-16 16:34

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0005_accountingexport_triggered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingexport',
            name='triggered_by',
            field=sage_desktop_api.models.fields.StringOptionsField(choices=[('WEBHOOK', 'WEBHOOK'), ('DASHBOARD_SYNC', 'DASHBOARD_SYNC'), ('DIRECT_EXPORT', 'DIRECT_EXPORT'), ('BACKGROUND_SCHEDULE', 'BACKGROUND_SCHEDULE'), ('INTERNAL', 'INTERNAL')], default='', help_text='Triggered by', max_length=255, null=True),
        ),
    ]
