# Generated by Django 4.2.22 on 2025-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0006_alter_accountingexport_triggered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingexport',
            name='re_attempt_export',
            field=models.BooleanField(default=False, help_text='Is re-attempt export'),
        ),
    ]
