# Generated by Django 4.2.25 on 2025-10-16 12:22

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0007_accountingexport_re_attempt_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingexport',
            name='type',
            field=sage_desktop_api.models.fields.StringOptionsField(choices=[('PURCHASE_INVOICE', 'PURCHASE_INVOICE'), ('DIRECT_COST', 'DIRECT_COST'), ('FETCHING_REIMBURSABLE_EXPENSES', 'FETCHING_REIMBURSABLE_EXPENSES'), ('FETCHING_CREDIT_CARD_EXPENSES', 'FETCHING_CREDIT_CARD_EXPENSES')], default='', help_text='Task type', max_length=255, null=True),
        ),
    ]
