# Generated by Django 4.2.26 on 2026-02-03 07:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_exports', '0008_alter_accountingexport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='mapping_error_accounting_export_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='List of accounting export IDs with mapping errors', size=None),
        ),
    ]
