# Generated by Django 4.1.2 on 2023-12-04 20:29

from django.db import migrations, models
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Sage300 Job Id', max_length=255)),
                ('job_name', sage_desktop_api.models.fields.StringNotNullField(help_text='Sage300 Job Name', max_length=255)),
                ('cost_code_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Sage300 Cost Code Id', max_length=255)),
                ('cost_code_name', sage_desktop_api.models.fields.StringNotNullField(help_text='Sage300 Cost Code Name', max_length=255)),
                ('name', sage_desktop_api.models.fields.StringNotNullField(help_text='Sage300 Cost Type Name', max_length=255)),
                ('cost_category_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Sage300 Category Id', max_length=255)),
                ('status', sage_desktop_api.models.fields.BooleanFalseField(default=False, help_text='Sage300 Cost Type Status')),
            ],
            options={
                'db_table': 'cost_category',
            },
        ),
    ]
