# Generated by Django 4.1.2 on 2023-10-27 09:30

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_sage300credential_importsetting_fylecredential_and_more'),
        ('accounting_exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', sage_desktop_api.models.fields.FloatNullField(help_text='Invoice amount', null=True)),
                ('accounting_date', sage_desktop_api.models.fields.StringNotNullField(help_text='Accounting date', max_length=255)),
                ('description', sage_desktop_api.models.fields.TextNotNullField(help_text='Invoice description')),
                ('tax_amount', sage_desktop_api.models.fields.FloatNullField(help_text='Tax amount', null=True)),
                ('vendor_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Vendor ID', max_length=255)),
                ('code', sage_desktop_api.models.fields.StringNotNullField(help_text='unique key for each document', max_length=15)),
                ('accounting_export', models.OneToOneField(help_text='Reference to AccountingExport model', on_delete=django.db.models.deletion.PROTECT, to='accounting_exports.accountingexport')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineitems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', sage_desktop_api.models.fields.FloatNullField(help_text='Invoice lineitem amount', null=True)),
                ('accounts_payable_account_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Accounts Payable Account Id', max_length=255)),
                ('description', sage_desktop_api.models.fields.TextNotNullField(help_text='Invoice lineitem description')),
                ('expense_account_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Expense Account Id', max_length=255)),
                ('job_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Job Id', max_length=255)),
                ('cost_code_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Cost Code Id', max_length=255)),
                ('category_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Category Id', max_length=255)),
                ('invoice_id', models.ForeignKey(help_text='Reference to Invoice model', on_delete=django.db.models.deletion.PROTECT, to='sage300.invoice')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'invoice_lineitems',
            },
        ),
        migrations.CreateModel(
            name='DirectCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', sage_desktop_api.models.fields.FloatNullField(help_text='Invoice amount', null=True)),
                ('code', sage_desktop_api.models.fields.StringNotNullField(help_text='Code Id', max_length=255)),
                ('job_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Job Id', max_length=255)),
                ('cost_code_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Cost Code Id', max_length=255)),
                ('category_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Category Id', max_length=255)),
                ('credit_card_account_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Credit Card Account Id', max_length=255)),
                ('debit_card_account_id', sage_desktop_api.models.fields.StringNotNullField(help_text='Debit Card Account Id', max_length=255)),
                ('transaction_date', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Transaction Date', null=True)),
                ('description', sage_desktop_api.models.fields.TextNotNullField(help_text='Direct Costs description')),
                ('transaction_type', sage_desktop_api.models.fields.IntegerNullField(help_text='Transaction Type', null=True)),
                ('accounting_export', models.OneToOneField(help_text='Reference to AccountingExport model', on_delete=django.db.models.deletion.PROTECT, to='accounting_exports.accountingexport')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'direct_cost',
            },
        ),
    ]
