# Generated by Django 4.1.2 on 2023-11-16 11:50

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0001_initial'),
        ('accounting_exports', '0001_initial'),
        ('sage300', '0002_costcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('baseexportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sage300.baseexportmodel')),
                ('accounting_date', sage_desktop_api.models.fields.CustomDateTimeField(help_text='accounting date of purchase invoice', null=True)),
                ('amount', sage_desktop_api.models.fields.FloatNullField(help_text='Total Amount of the invoice', null=True)),
                ('code', sage_desktop_api.models.fields.StringNullField(help_text='unique code for invoice', max_length=10, null=True)),
                ('description', sage_desktop_api.models.fields.TextNotNullField(help_text='description for the invoice')),
                ('invoice_date', sage_desktop_api.models.fields.CustomDateTimeField(help_text='date of invoice', null=True)),
                ('tax_amount', sage_desktop_api.models.fields.FloatNullField(help_text='total tax amount of the invoice', null=True)),
                ('vendor_id', sage_desktop_api.models.fields.StringNullField(help_text='id of vendor', max_length=255, null=True)),
                ('accounting_export', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='accounting_exports.accountingexport')),
            ],
            options={
                'db_table': 'purchase_invoices',
            },
            bases=('sage300.baseexportmodel',),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLineitems',
            fields=[
                ('baseexportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sage300.baseexportmodel')),
                ('accounts_payable_account_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of accounts payable account', max_length=255, null=True)),
                ('amount', sage_desktop_api.models.fields.FloatNullField(help_text='Amount of the invoice', null=True)),
                ('category_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of category', max_length=255, null=True)),
                ('commitment_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of commitment', max_length=255, null=True)),
                ('cost_code_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of cost code', max_length=255, null=True)),
                ('description', sage_desktop_api.models.fields.TextNotNullField(help_text='description for the invoice')),
                ('job_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of job', max_length=255, null=True)),
                ('tax_amount', sage_desktop_api.models.fields.FloatNullField(help_text='tax amount of the invoice', null=True)),
                ('tax_group_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of tax group', max_length=255, null=True)),
                ('standard_category_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of standard category', max_length=255, null=True)),
                ('standard_cost_code_id', sage_desktop_api.models.fields.StringNullField(help_text='destination id of standard cost code', max_length=255, null=True)),
                ('expense', models.OneToOneField(help_text='Reference to Expense', on_delete=django.db.models.deletion.PROTECT, to='fyle.expense')),
                ('purchase_invoice', models.ForeignKey(help_text='Reference to PurchaseInvoice', on_delete=django.db.models.deletion.PROTECT, to='sage300.purchaseinvoice')),
            ],
            options={
                'db_table': 'purchase_invoice_lineitems',
            },
            bases=('sage300.baseexportmodel',),
        ),
    ]
