# Generated by Django 4.1.2 on 2024-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage300', '0002_purchaseinvoicelineitems_commitment_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Is Imported'),
        ),
    ]
