# Generated by Django 4.1.2 on 2024-06-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sage300', '0003_costcategory_is_imported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoicelineitems',
            old_name='accounts_payable_account_id',
            new_name='expense_account_id',
        ),
    ]
