# Generated by Django 4.1.2 on 2023-11-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_lastexportdetail'),
        ('sage300', '0003_purchaseinvoice_purchaseinvoicelineitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='workspace',
            field=models.ForeignKey(default=1, help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoicelineitems',
            name='workspace',
            field=models.ForeignKey(default='1', help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace'),
            preserve_default=False,
        ),
    ]
