# Generated by Django 4.1.2 on 2024-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage300', '0006_alter_purchaseinvoicelineitems_expense_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='cost_category_code',
            field=models.CharField(help_text='Cost_Category - Code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='costcategory',
            name='cost_code_code',
            field=models.CharField(help_text='Cost_Code - Code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='costcategory',
            name='job_code',
            field=models.CharField(help_text='Job - Code', max_length=255, null=True),
        ),
    ]
