# Generated by Django 3.1.14 on 2023-10-20 14:00

import apps.workspaces.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', sage_desktop_api.models.fields.StringNotNullField(help_text='Name of the workspace', max_length=255)),
                ('org_id', models.CharField(help_text='org id', max_length=255, unique=True)),
                ('last_synced_at', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Datetime when expenses were pulled last', null=True)),
                ('ccc_last_synced_at', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Datetime when ccc expenses were pulled last', null=True)),
                ('source_synced_at', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Datetime when source dimensions were pulled', null=True)),
                ('destination_synced_at', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Datetime when destination dimensions were pulled', null=True)),
                ('onboarding_state', sage_desktop_api.models.fields.StringOptionsField(choices=[('CONNECTION', 'CONNECTION'), ('EXPORT_SETTINGS', 'EXPORT_SETTINGS'), ('IMPORT_SETTINGS', 'IMPORT_SETTINGS'), ('ADVANCED_CONFIGURATION', 'ADVANCED_CONFIGURATION'), ('COMPLETE', 'COMPLETE')], default=apps.workspaces.models.get_default_onboarding_state, help_text='Onboarding status of the workspace', max_length=50, null=True)),
                ('sage300_accounts_last_synced_at', sage_desktop_api.models.fields.CustomDateTimeField(help_text='sage accounts last synced at time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('user', models.ManyToManyField(help_text='Reference to users table', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='Sage300Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('identifier', sage_desktop_api.models.fields.StringNotNullField(help_text='sage300 identifier', max_length=255)),
                ('username', sage_desktop_api.models.fields.StringNotNullField(help_text='sage300 username', max_length=255)),
                ('password', sage_desktop_api.models.fields.StringNotNullField(help_text='sage300 password', max_length=255)),
                ('api_key', sage_desktop_api.models.fields.StringNotNullField(help_text='sage300 api key', max_length=255)),
                ('api_secret', sage_desktop_api.models.fields.StringNotNullField(help_text='sage300 api secret', max_length=255)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'sage300_credentials',
            },
        ),
        migrations.CreateModel(
            name='ImportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('import_categories', sage_desktop_api.models.fields.BooleanFalseField(default=True, help_text='toggle for import of chart of accounts from sage300')),
                ('import_vendors_as_merchants', sage_desktop_api.models.fields.BooleanFalseField(default=True, help_text='toggle for import of vendors as merchant from sage300')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'import_settings',
            },
        ),
        migrations.CreateModel(
            name='FyleCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('refresh_token', sage_desktop_api.models.fields.TextNotNullField(help_text='Fyle refresh token')),
                ('cluster_domain', sage_desktop_api.models.fields.StringNullField(help_text='Fyle cluster domain', max_length=255, null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'fyle_credentials',
            },
        ),
        migrations.CreateModel(
            name='ExportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('reimbursable_expenses_export_type', sage_desktop_api.models.fields.StringOptionsField(choices=[('PURCHASE_INVOICE', 'PURCHASE_INVOICE'), ('DIRECT_COST', 'DIRECT_COST')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_bank_account_name', sage_desktop_api.models.fields.StringNullField(help_text='Bank account name', max_length=255, null=True)),
                ('default_back_account_id', sage_desktop_api.models.fields.StringNullField(help_text='Bank Account ID', max_length=255, null=True)),
                ('reimbursable_expense_state', sage_desktop_api.models.fields.StringOptionsField(choices=[('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('CLOSED', 'CLOSED')], default='', help_text='string field with options', max_length=255, null=True)),
                ('reimbursable_expense_date', sage_desktop_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('CREATED_AT', 'created_at'), ('SPENT_AT', 'spent_at')], default='', help_text='string field with options', max_length=255, null=True)),
                ('reimbursable_expense_grouped_by', sage_desktop_api.models.fields.StringOptionsField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_export_type', sage_desktop_api.models.fields.StringOptionsField(choices=[('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_state', sage_desktop_api.models.fields.StringOptionsField(choices=[('APPROVED', 'APPROVED'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_credit_card_account_name', sage_desktop_api.models.fields.StringNullField(help_text='Credit card account name', max_length=255, null=True)),
                ('default_credit_card_account_id', sage_desktop_api.models.fields.StringNullField(help_text='Credit Card Account ID', max_length=255, null=True)),
                ('credit_card_expense_grouped_by', sage_desktop_api.models.fields.StringOptionsField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_date', sage_desktop_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('POSTED_AT', 'posted_at'), ('CREATED_AT', 'created_at')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_vendor_name', sage_desktop_api.models.fields.StringNullField(help_text='default Vendor Name', max_length=255, null=True)),
                ('default_vendor_id', sage_desktop_api.models.fields.StringNullField(help_text='default Vendor Id', max_length=255, null=True)),
                ('auto_create_vendor', sage_desktop_api.models.fields.BooleanFalseField(default=True, help_text='Auto create vendor')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'export_settings',
            },
        ),
        migrations.CreateModel(
            name='AdvancedSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('expense_memo_structure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Array of fields in memo', null=True, size=None)),
                ('schedule_is_enabled', sage_desktop_api.models.fields.BooleanFalseField(default=True, help_text='Boolean to check if schedule is enabled')),
                ('schedule_start_datetime', sage_desktop_api.models.fields.CustomDateTimeField(help_text='Schedule start date and time', null=True)),
                ('schedule_id', sage_desktop_api.models.fields.StringNullField(help_text='Schedule id', max_length=255, null=True)),
                ('interval_hours', sage_desktop_api.models.fields.IntegerNullField(help_text='Interval in hours', null=True)),
                ('emails_selected', sage_desktop_api.models.fields.CustomJsonField(default=list, help_text='Emails Selected For Email Notification', null=True)),
                ('emails_added', sage_desktop_api.models.fields.CustomJsonField(default=list, help_text='Emails Selected For Email Notification', null=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'advanced_settings',
            },
        ),
    ]
