# Generated by Django 3.1.14 on 2023-10-17 07:29

import apps.workspaces.helpers
import apps.workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', apps.workspaces.helpers.StringNotNullField(help_text='Name of the workspace', max_length=255)),
                ('org_id', models.CharField(help_text='org id', max_length=255, unique=True)),
                ('fyle_currency', apps.workspaces.helpers.StringNullField(help_text='Fyle Currency', max_length=5, null=True)),
                ('last_synced_at', apps.workspaces.helpers.CustomDateTimeField(help_text='Datetime when expenses were pulled last', null=True)),
                ('ccc_last_synced_at', apps.workspaces.helpers.CustomDateTimeField(help_text='Datetime when ccc expenses were pulled last', null=True)),
                ('source_synced_at', apps.workspaces.helpers.CustomDateTimeField(help_text='Datetime when source dimensions were pulled', null=True)),
                ('destination_synced_at', apps.workspaces.helpers.CustomDateTimeField(help_text='Datetime when destination dimensions were pulled', null=True)),
                ('onboarding_state', apps.workspaces.helpers.StringOptionsField(choices=[('CONNECTION', 'CONNECTION'), ('EXPORT_SETTINGS', 'EXPORT_SETTINGS'), ('IMPORT_SETTINGS', 'IMPORT_SETTINGS'), ('ADVANCED_CONFIGURATION', 'ADVANCED_CONFIGURATION'), ('COMPLETE', 'COMPLETE')], default=apps.workspaces.models.get_default_onboarding_state, help_text='Onboarding status of the workspace', max_length=50, null=True)),
                ('sage300_accounts_last_synced_at', apps.workspaces.helpers.CustomDateTimeField(help_text='sage accounts last synced at time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('user', models.ManyToManyField(help_text='Reference to users table', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
    ]
