# Generated by Django 4.1.2 on 2023-12-11 14:53

from django.db import migrations, models
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastexportdetail',
            name='failed_expense_groups_count',
        ),
        migrations.RemoveField(
            model_name='lastexportdetail',
            name='successful_expense_groups_count',
        ),
        migrations.RemoveField(
            model_name='lastexportdetail',
            name='total_expense_groups_count',
        ),
        migrations.AddField(
            model_name='lastexportdetail',
            name='failed_accounting_exports_count',
            field=models.IntegerField(help_text='count of failed accounting_exports ', null=True),
        ),
        migrations.AddField(
            model_name='lastexportdetail',
            name='successful_accounting_exports_count',
            field=models.IntegerField(help_text='count of successful accounting_exports ', null=True),
        ),
        migrations.AddField(
            model_name='lastexportdetail',
            name='total_accounting_exports_count',
            field=models.IntegerField(help_text='Total count of accounting exports exported', null=True),
        ),
        migrations.AlterField(
            model_name='exportsetting',
            name='credit_card_expense_export_type',
            field=sage_desktop_api.models.fields.StringOptionsField(choices=[('PURCHASE_INVOICE', 'PURCHASE_INVOICE'), ('DIRECT_COST', 'DIRECT_COST')], default='', help_text='string field with options', max_length=255, null=True),
        ),
    ]
