# Generated by Django 3.1.14 on 2023-10-18 12:42

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sage300Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('identifier', sage_desktop_api.helpers.StringNotNullField(help_text='sage300 identifier', max_length=255)),
                ('username', sage_desktop_api.helpers.StringNotNullField(help_text='sage300 username', max_length=255)),
                ('password', sage_desktop_api.helpers.StringNotNullField(help_text='sage300 password', max_length=255)),
                ('api_key', sage_desktop_api.helpers.StringNotNullField(help_text='sage300 api key', max_length=255)),
                ('api_secret', sage_desktop_api.helpers.StringNotNullField(help_text='sage300 api secret', max_length=255)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'sage300_credentials',
            },
        ),
    ]
