# Generated by Django 4.1.2 on 2023-10-27 07:59

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_remove_exportsetting_auto_create_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsetting',
            name='default_reimbursable_account_id',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Reimbursable Account ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='default_reimbursable_account_name',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Reimbursable account name', max_length=255, null=True),
        ),
    ]
