# Generated by Django 4.1.2 on 2023-11-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_sage300credential_importsetting_fylecredential_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='ccc_last_synced_at',
            new_name='credit_card_last_synced_at',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='last_synced_at',
            new_name='reimbursable_last_synced_at',
        ),
        migrations.RemoveField(
            model_name='advancedsetting',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='advancedsetting',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.schedule'),
        ),
    ]
