# Generated by Django 3.2.22 on 2023-10-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_fylecredential'),
        ('workspaces', '0002_sage300credentials'),
    ]

    operations = [
    ]
