# Generated by Django 4.1.2 on 2023-11-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_importsetting_workspace'),
        ('workspaces', '0003_rename_ccc_last_synced_at_workspace_credit_card_last_synced_at_and_more'),
    ]

    operations = [
    ]
