# Generated by Django 4.1.2 on 2023-11-14 09:46

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_remove_advancedsetting_schedule_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsetting',
            name='sync_sage_300_to_fyle_payments',
            field=sage_desktop_api.models.fields.BooleanFalseField(default=False, help_text='Sync sage 300 to fyle payments'),
        ),
    ]
