# Generated by Django 4.1.2 on 2024-02-08 09:47

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_advancedsetting_add_commitment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedsetting',
            name='add_commitment_details',
        ),
        migrations.AddField(
            model_name='importsetting',
            name='add_commitment_details',
            field=sage_desktop_api.models.fields.BooleanFalseField(default=False, help_text='Add commitment details'),
        ),
    ]
