# Generated by Django 3.2.22 on 2023-10-17 18:43

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_merge_0002_fylecredential_0002_sage300credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sage300credentials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=255, null=True)),
                ('reimbursable_expenses_export_type', sage_desktop_api.helpers.StringOptionsField(choices=[('PURCHASE_INVOICE', 'PURCHASE_INVOICE'), ('DIRECT_COST', 'DIRECT_COST')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_bank_account_name', sage_desktop_api.helpers.StringNullField(help_text='Bank account name', max_length=255, null=True)),
                ('default_back_account_id', models.CharField(help_text='Account ID', max_length=255)),
                ('reimbursable_expense_state', sage_desktop_api.helpers.StringOptionsField(choices=[('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('CLOSED', 'CLOSED')], default='', help_text='string field with options', max_length=255, null=True)),
                ('reimbursable_expense_date', sage_desktop_api.helpers.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('CREATED_AT', 'created_at'), ('SPENT_AT', 'spent_at')], default='', help_text='string field with options', max_length=255, null=True)),
                ('reimbursable_expense_grouped_by', sage_desktop_api.helpers.StringOptionsField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_export_type', sage_desktop_api.helpers.StringOptionsField(choices=[('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_state', sage_desktop_api.helpers.StringOptionsField(choices=[('APPROVED', 'APPROVED'), ('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAID', 'PAID')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_credit_card_account_name', sage_desktop_api.helpers.StringNullField(help_text='Credit card account name', max_length=255, null=True)),
                ('default_credit_card_account_id', sage_desktop_api.helpers.StringNullField(help_text='Credit Card Account ID', max_length=255, null=True)),
                ('credit_card_expense_grouped_by', sage_desktop_api.helpers.StringOptionsField(choices=[('REPORT', 'report_id'), ('EXPENSE', 'expense_id')], default='', help_text='string field with options', max_length=255, null=True)),
                ('credit_card_expense_date', sage_desktop_api.helpers.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('POSTED_AT', 'posted_at'), ('CREATED_AT', 'created_at')], default='', help_text='string field with options', max_length=255, null=True)),
                ('default_vendor_name', sage_desktop_api.helpers.StringNullField(help_text='default Vendor Name', max_length=255, null=True)),
                ('default_vendor_id', sage_desktop_api.helpers.StringNullField(help_text='default Vendor Id', max_length=255, null=True)),
                ('auto_create_vendor', sage_desktop_api.helpers.BooleanFalseField(default=True)),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'export_settings',
            },
        ),
    ]
