# Generated by Django 4.1.2 on 2024-06-25 05:00

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_remove_advancedsetting_add_commitment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportsetting',
            name='default_ccc_account_payable_id',
            field=sage_desktop_api.models.fields.StringNullField(help_text='CCC Credit Card Account Payable ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='default_ccc_account_payable_name',
            field=sage_desktop_api.models.fields.StringNullField(help_text='CCC Credit card account payable name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='default_reimbursable_account_payable_id',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Reimbursable account payable id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportsetting',
            name='default_reimbursable_account_payable_name',
            field=sage_desktop_api.models.fields.StringNullField(help_text='Reimbursable account payable name', max_length=255, null=True),
        ),
    ]
