# Generated by Django 4.1.2 on 2024-07-15 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_exportsetting_default_ccc_account_payable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsetting',
            name='import_code_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('JOB', 'JOB'), ('VENDOR', 'VENDOR'), ('ACCOUNT', 'ACCOUNT'), ('COST_CODE', 'COST_CODE'), ('COST_CATEGORY', 'COST_CATEGORY')], max_length=100), blank=True, default=list, help_text='Array Field to store code-naming preference', size=None),
        ),
    ]
