# Generated by Django 4.2.20 on 2025-06-11 13:20

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_add_created_at_to_user_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsetting',
            name='is_real_time_export_enabled',
            field=sage_desktop_api.models.fields.BooleanFalseField(default=False, help_text='Is real time export enabled'),
        ),
    ]
