# Generated by Django 4.2.20 on 2025-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_advancedsetting_is_real_time_export_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sage300credential',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Marks if credentials are expired'),
        ),
    ]
