# Generated by Django 4.2.25 on 2025-10-16 12:22

from django.db import migrations, models
import django.db.models.deletion
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_sage300credential_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sage300credential',
            name='is_expired',
            field=sage_desktop_api.models.fields.BooleanFalseField(default=False, help_text='Marks if credentials are expired'),
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('export_via_rabbitmq', models.BooleanField(default=False, help_text='Enable export via rabbitmq')),
                ('fyle_webhook_sync_enabled', models.BooleanField(default=False, help_text='Enable fyle attribute webhook sync')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'feature_configs',
            },
        ),
    ]
