# Generated by Django 4.2.26 on 2025-12-17 08:13

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_alter_featureconfig_fyle_webhook_sync_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsetting',
            name='credit_card_expense_date',
            field=sage_desktop_api.models.fields.StringOptionsField(choices=[('LAST_SPENT_AT', 'last_spent_at'), ('POSTED_AT', 'posted_at'), ('CURRENT_DATE', 'current_date')], default='', help_text='string field with options', max_length=255, null=True),
        ),
    ]
