# Generated by Django 4.2.27 on 2026-01-20 10:54

from django.db import migrations
import sage_desktop_api.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_alter_exportsetting_credit_card_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='org_settings',
            field=sage_desktop_api.models.fields.CustomJsonField(default=list, help_text='Org Settings', null=True),
        ),
    ]
