# Generated by Django 4.2.27 on 2026-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_alter_exportsetting_credit_card_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='org_settings',
            field=models.JSONField(default=dict, help_text='Org Settings'),
        ),
    ]
