# Generated by Django 4.2.28 on 2026-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_workspace_org_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='is_job_status_sync_enabled',
            field=models.BooleanField(default=True, help_text='Use Sage 300 CRE job status for filtering jobs during sync'),
        ),
    ]
